<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Opengento\Document\Api\Data\DocumentTypeInterface;
use Opengento\DocumentSearch\ViewModel\Search\Term;
use Opengento\DocumentWidget\ViewModel\DocumentType;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var Term $searchTerm */
$searchTerm = $block->getData('searchTerm');
/** @var DocumentType $documentTypeHelper */
$documentTypeHelper = $block->getData('documentTypeHelper');

/** @var DocumentTypeInterface[] $activeTypes */
$activeTypes = [];
foreach ($documentTypeHelper->getList() as $documentType) {
    if ($searchTerm->isChecked($documentType->getId())) {
        $activeTypes[$documentType->getId()] = $documentType;
    }
}
?>
<?php if ($activeTypes) :?>
    <div class="filter-current">
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-count="<?= count($activeTypes) ?>"><?= $escaper->escapeHtml(__('Now Filtering by')) ?></strong>
        <ol class="items">
            <?php foreach ($activeTypes as $activeType) : ?>
                <li class="item">
                    <span class="filter-label"><?= $escaper->escapeHtml(__('Type')) ?></span>
                    <span class="filter-value"><?= $escaper->escapeHtml($activeType->getName()) ?></span>
                    <a class="action remove"
                       title="<?= $escaper->escapeHtmlAttr(__('Remove %1', $activeType->getName())) ?>"
                       href="<?= $block->getUrl('*/*/*', ['_current' => true, '_query' => ['types' => array_diff(array_keys($activeTypes), [$activeType->getId()])]]) ?>">
                        <span><?= $escaper->escapeHtml(__('Remove This Item')) ?></span>
                    </a>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>

<?php if (count($documentTypeHelper->getList())): ?>
    <div class="block filter">
        <div class="title">
            <strong><?= $escaper->escapeHtml(__('Filter By')) ?></strong>
        </div>
        <div class="content">
            <strong class="subtitle"><?= $escaper->escapeHtml(__('Document Options')) ?></strong>
            <dl class="options" id="narrow-by-list2">
                <dt><?= $escaper->escapeHtml(__('Type')) ?></dt>
                <dd>
                    <ol class="items">
                        <?php foreach ($documentTypeHelper->getList() as $documentType): ?>
                            <li class="item">
                                <?php if ($searchTerm->isChecked($documentType->getId())): ?>
                                    <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_query' => ['types' => array_diff(array_keys($activeTypes), [$documentType->getId()])]])) ?>" class="active" rel="nofollow">
                                <?php else: ?>
                                    <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_query' => ['types' => array_merge(array_keys($activeTypes), [$documentType->getId()])]])) ?>" rel="nofollow">
                                <?php endif; ?>
                                    <?= $escaper->escapeHtml($documentType->getName()) ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
